backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: jackohara
    api_key: 182941528276584

collections:
  - name: "announcement"
    label: "Announcements"
    folder: "src/pages/news/announcements"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          required: true,
          default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Author", name: "author", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "roundup"
    label: "Roundups"
    folder: "src/pages/news/roundups"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          required: true,
          default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Author", name: "author", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "training"
    label: "Training"
    folder: "src/pages/training"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          required: true,
          default: "news-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "juniors"
    label: "Juniors Welcome Page"
    folder: "src/pages/juniors"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          required: true,
          default: "default-template",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
